// ******
// EXTRAS
// ******

extrasList = [
  {
    name: "Cursed Gold",
    type: "heirloom",
    status: "",
    image: "",
    setup: "Cursed Gold",
  },
  {
    name: "Goat",
    type: "heirloom",
    status: "",
    image: "",
    setup: "Goat",
  },
  {
    name: "Haunted Mirror and Ghost",
    type: "heirloom",
    status: "",
    image: "",
    setup: "Haunted Mirror and Ghost",
  },
  {
    name: "Lucky Coin",
    type: "heirloom",
    status: "",
    image: "",
    setup: "Lucky Coin",
  },
  {
    name: "Magic Lamp",
    type: "heirloom",
    status: "",
    image: "",
    setup: "Magic Lamp and Wishes",
  },
  {
    name: "Pasture",
    type: "heirloom",
    status: "",
    image: "",
    setup: "Pasture",
  },
  {
    name: "Pouch",
    type: "heirloom",
    status: "",
    image: "",
    setup: "Pouch",
  },
  {
    name: "Start w/ coin",
    type: "start",
    status: "",
    image: "",
    setup: "Start w/ coin",
  },
  {
    name: "Advance",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Alms",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Annex",
    type: "event",
    status: "",
    image: "",
    setup: "Debt",
  },
  {
    name: "Ball",
    type: "event",
    status: "",
    image: "",
    setup: "-coin",
  },
  {
    name: "Banquet",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Bonfire",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Borrow",
    type: "event",
    status: "",
    image: "",
    setup: "-card",
  },
  {
    name: "Conquest",
    type: "event",
    status: "",
    image: "",
    setup: "Victory",
  },
  {
    name: "Delve",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Dominate",
    type: "event",
    status: "",
    image: "",
    setup: "Victory",
  },
  {
    name: "Donate",
    type: "event",
    status: "",
    image: "",
    setup: "Debt",
  },
  {
    name: "Expedition",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Ferry",
    type: "event",
    status: "",
    image: "",
    setup: "-2 Cost",
  },
  {
    name: "Inheritance",
    type: "event",
    status: "",
    image: "",
    setup: "Mat",
  },
  {
    name: "Lost Arts",
    type: "event",
    status: "",
    image: "",
    setup: "Action Token",
  },
  {
    name: "Mission",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Pathfinding",
    type: "event",
    status: "",
    image: "",
    setup: "+Card",
  },
  {
    name: "Pilgrimage",
    type: "event",
    status: "",
    image: "",
    setup: "Journey",
  },
  {
    name: "Plan",
    type: "event",
    status: "",
    image: "",
    setup: "Trashing Token",
  },
  {
    name: "Quest",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Raid",
    type: "event",
    status: "",
    image: "",
    setup: "-card",
  },
  {
    name: "Ritual",
    type: "event",
    status: "",
    image: "",
    setup: "Victory",
  },
  {
    name: "Salt the Earth",
    type: "event",
    status: "",
    image: "",
    setup: "Victory",
  },
  {
    name: "Save",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Scouting Party",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Seaway",
    type: "event",
    status: "",
    image: "",
    setup: "Buy Token",
  },
  {
    name: "Summon",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Tax",
    type: "event",
    status: "",
    image: "",
    setup: "Add Debt to Each Supply",
  },
  {
    name: "Trade",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Training",
    type: "event",
    status: "",
    image: "",
    setup: "+Coin",
  },
  {
    name: "Travelling Fair",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Triumph",
    type: "event",
    status: "",
    image: "",
    setup: "Victory and Debt",
  },
  {
    name: "Wedding",
    type: "event",
    status: "",
    image: "",
    setup: "Victory and Debt",
  },
  {
    name: "Windfall",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Academy",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Barracks",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Canal",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Capitalism",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Cathedral",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Citadel",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "City Gate",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Crop Rotation",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Exploration",
    type: "project",
    status: "",
    image: "",
    setup: "Coffers and Villagers",
  },
  {
    name: "Fair",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Fleet",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Guildhall",
    type: "project",
    status: "",
    image: "",
    setup: "Coffers",
  },
  {
    name: "Innovation",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Pageant",
    type: "project",
    status: "",
    image: "",
    setup: "Coffers",
  },
  {
    name: "Piazza",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Road Network",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Sewers",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Silos",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Sinister Plot",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Star Chart",
    type: "project",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Aqueduct",
    type: "landmark",
    status: "",
    image: "",
    setup: "8 Victory on Silver and Gold",
  },
  {
    name: "Arena",
    type: "landmark",
    status: "",
    image: "",
    setup: "6 Victory per player",
  },
  {
    name: "Bandit Fort",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Basilica",
    type: "landmark",
    status: "",
    image: "",
    setup: "6 Victory per player",
  },
  {
    name: "Baths",
    type: "landmark",
    status: "",
    image: "",
    setup: "6 Victory per player",
  },
  {
    name: "Battlefield",
    type: "landmark",
    status: "",
    image: "",
    setup: "6 Victory per player",
  },
  {
    name: "Colonnade",
    type: "landmark",
    status: "",
    image: "",
    setup: "6 Victory per player",
  },
  {
    name: "Defiled Shrine",
    type: "landmark",
    status: "",
    image: "",
    setup: "2 Victory on each non-gathering action in supply",
  },
  {
    name: "Fountain",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Keep",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Labyrinth",
    type: "landmark",
    status: "",
    image: "",
    setup: "6 Victory per player",
  },
  {
    name: "Mountain Pass",
    type: "landmark",
    status: "",
    image: "",
    setup: "Debt and Victory and put on Province",
  },
  {
    name: "Museum",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Orchard",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Palace",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Tomb",
    type: "landmark",
    status: "",
    image: "",
    setup: "Victory",
  },
  {
    name: "Tower",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Triumphal Arch",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Wall",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Wolf Den",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Obelisk",
    type: "landmark",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Alliance",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Banish",
    type: "event",
    status: "",
    image: "",
    setup: "Mat",
  },
  {
    name: "Bargain",
    type: "event",
    status: "",
    image: "",
    setup: "Horses",
  },
  {
    name: "Commerce",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Delay",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Demand",
    type: "event",
    status: "",
    image: "",
    setup: "Horses",
  },
  {
    name: "Desperation",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Enclave",
    type: "event",
    status: "",
    image: "",
    setup: "Mat",
  },
  {
    name: "Enhance",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Gamble",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Invest",
    type: "event",
    status: "",
    image: "",
    setup: "Mat",
  },
  {
    name: "March",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Populate",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Pursue",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Reap",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Ride",
    type: "event",
    status: "",
    image: "",
    setup: "Horses",
  },
  {
    name: "Seize the Day",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Stampede",
    type: "event",
    status: "",
    image: "",
    setup: "Horses",
  },
  {
    name: "Toil",
    type: "event",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Transport",
    type: "event",
    status: "",
    image: "",
    setup: "Mat",
  },
  {
    name: "Way of the Butterfly",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Camel",
    type: "Way",
    status: "",
    image: "",
    setup: "Mat",
  },
  {
    name: "Way of the Chameleon",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Frog",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Goat",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Horse",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Mole",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Monkey",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Mouse",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Mule",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Otter",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Owl",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Ox",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Pig",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Rat",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Seal",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Sheep",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Squirrel",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Turtle",
    type: "Way",
    status: "",
    image: "",
    setup: "",
  },
  {
    name: "Way of the Worm",
    type: "Way",
    status: "",
    image: "",
    setup: "Mat",
  },
];

export default extrasList;
